"""Relation between child and order item

Revision ID: 0872e929f6d1
Revises: 8a018563c290
Create Date: 2025-03-26 01:12:13.351156

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0872e929f6d1'
down_revision = '8a018563c290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
