"""add

Revision ID: 1aab9f5d5cc5
Revises: 672ac025033b
Create Date: 2025-03-12 07:51:43.580423

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1aab9f5d5cc5'
down_revision = '672ac025033b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
