"""add

Revision ID: 2f4e6c6eb731
Revises: 0b4d3c442014
Create Date: 2025-03-06 06:06:11.522389

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f4e6c6eb731'
down_revision = '0b4d3c442014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('client_group_id', sa.Uuid(), nullable=False))
    op.add_column('payment', sa.Column('plan_id', sa.Uuid(), nullable=True))
    op.drop_constraint('payment_subscription_id_fkey', 'payment', type_='foreignkey')
    op.drop_constraint('payment_client_id_fkey', 'payment', type_='foreignkey')
    op.create_foreign_key(None, 'payment', 'clientgroup', ['client_group_id'], ['id'])
    op.create_foreign_key(None, 'payment', 'plan', ['plan_id'], ['id'])
    op.drop_column('payment', 'client_id')
    op.drop_column('payment', 'subscription_id')
    op.add_column('reservation', sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('visit', sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visit', 'details')
    op.drop_column('reservation', 'details')
    op.add_column('payment', sa.Column('subscription_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('payment', sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.create_foreign_key('payment_client_id_fkey', 'payment', 'client', ['client_id'], ['id'])
    op.create_foreign_key('payment_subscription_id_fkey', 'payment', 'subscription', ['subscription_id'], ['id'])
    op.drop_column('payment', 'plan_id')
    op.drop_column('payment', 'client_group_id')
    # ### end Alembic commands ###
