"""orgs

Revision ID: 426421ee7e02
Revises: 5d001c532727
Create Date: 2024-10-03 04:10:15.640878

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '426421ee7e02'
down_revision = '5d001c532727'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_personal', sa.Boolean(), nullable=False),
    sa.Column('token', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_email'), 'organization', ['email'], unique=True)
    op.create_table('organizationuser',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('organization_id', 'user_id')
    )
    op.add_column('chat', sa.Column('organization_id', sa.Uuid(), nullable=False))
    op.drop_constraint('chat_user_id_fkey', 'chat', type_='foreignkey')
    op.create_foreign_key(None, 'chat', 'organization', ['organization_id'], ['id'])
    op.drop_column('chat', 'user_id')
    op.add_column('item', sa.Column('organization_id', sa.Uuid(), nullable=False))
    op.drop_constraint('item_owner_id_fkey', 'item', type_='foreignkey')
    op.create_foreign_key(None, 'item', 'organization', ['organization_id'], ['id'])
    op.drop_column('item', 'owner_id')
    op.add_column('project', sa.Column('organization_id', sa.Uuid(), nullable=False))
    op.alter_column('project', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('project_user_id_fkey', 'project', type_='foreignkey')
    op.create_foreign_key(None, 'project', 'organization', ['organization_id'], ['id'])
    op.drop_column('project', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.create_foreign_key('project_user_id_fkey', 'project', 'user', ['user_id'], ['id'])
    op.alter_column('project', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('project', 'organization_id')
    op.add_column('item', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_foreign_key('item_owner_id_fkey', 'item', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('item', 'organization_id')
    op.add_column('chat', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chat', type_='foreignkey')
    op.create_foreign_key('chat_user_id_fkey', 'chat', 'user', ['user_id'], ['id'])
    op.drop_column('chat', 'organization_id')
    op.drop_table('organizationuser')
    op.drop_index(op.f('ix_organization_email'), table_name='organization')
    op.drop_table('organization')
    # ### end Alembic commands ###
