"""add

Revision ID: 4cac45a938be
Revises: 93cb953b3ec0
Create Date: 2025-03-13 08:25:56.720796

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4cac45a938be'
down_revision = '93cb953b3ec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_client_email', table_name='client')
    op.create_index(op.f('ix_client_email'), 'client', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_email'), table_name='client')
    op.create_index('ix_client_email', 'client', ['email'], unique=True)
    # ### end Alembic commands ###
