"""add

Revision ID: 5574646226ff
Revises: d315f479932e
Create Date: 2025-03-02 08:14:55.942794

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5574646226ff'
down_revision = 'd315f479932e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('client_gropup_id', sa.Uuid(), nullable=False))
    op.add_column('reservation', sa.Column('client_amount', sa.Integer(), nullable=True))
    op.drop_constraint('reservation_client_id_fkey', 'reservation', type_='foreignkey')
    op.create_foreign_key(None, 'reservation', 'clientgroup', ['client_gropup_id'], ['id'])
    op.drop_column('reservation', 'client_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reservation', type_='foreignkey')
    op.create_foreign_key('reservation_client_id_fkey', 'reservation', 'client', ['client_id'], ['id'])
    op.drop_column('reservation', 'client_amount')
    op.drop_column('reservation', 'client_gropup_id')
    # ### end Alembic commands ###
