"""Modify form data field to save json serialized as strings

Revision ID: 7494ace7207a
Revises: cbdde05d2fa4
Create Date: 2025-03-21 19:25:34.074280

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7494ace7207a'
down_revision = 'cbdde05d2fa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('form', 'form_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('form', 'form_data',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###
