"""add

Revision ID: 7bc69ed2c214
Revises: 2f4e6c6eb731
Create Date: 2025-03-11 04:41:57.979190

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7bc69ed2c214'
down_revision = '2f4e6c6eb731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('purchased_addons', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('plan', sa.Column('addons', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan', 'addons')
    op.drop_column('payment', 'purchased_addons')
    # ### end Alembic commands ###
