"""a

Revision ID: 7f4e197ad981
Revises: 53e71b4901e5
Create Date: 2025-02-16 05:47:37.087290

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7f4e197ad981'
down_revision = '53e71b4901e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit', sa.Column('checked_out_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'visit', 'user', ['checked_out_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visit', type_='foreignkey')
    op.drop_column('visit', 'checked_out_by')
    # ### end Alembic commands ###
