"""Add column terms_accepted to User model

Revision ID: 8f4dc4cfb5ea
Revises: 4cac45a938be
Create Date: 2025-03-18 16:10:29.602318

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8f4dc4cfb5ea'
down_revision = '4cac45a938be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('terms_accepted', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'terms_accepted')
    # ### end Alembic commands ###
