"""add

Revision ID: 92489a5bb148
Revises: 426421ee7e02
Create Date: 2024-10-04 00:38:38.517906

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '92489a5bb148'
down_revision = '426421ee7e02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizationtoken',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=False),
    sa.Column('is_single_use', sa.Boolean(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizationtoken_token'), 'organizationtoken', ['token'], unique=True)
    op.add_column('organizationuser', sa.Column('roles', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('organizationuser', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizationuser', sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('organizationuser', 'roles')
    op.drop_index(op.f('ix_organizationtoken_token'), table_name='organizationtoken')
    op.drop_table('organizationtoken')
    # ### end Alembic commands ###
