"""add

Revision ID: 93cb953b3ec0
Revises: 1aab9f5d5cc5
Create Date: 2025-03-13 08:24:18.869959

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '93cb953b3ec0'
down_revision = '1aab9f5d5cc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('client', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('client', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
