"""add

Revision ID: a561558605e7
Revises: 5574646226ff
Create Date: 2025-03-02 23:43:34.632119

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a561558605e7'
down_revision = '5574646226ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('identification', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('reservation', sa.Column('client_group_id', sa.Uuid(), nullable=False))
    op.alter_column('reservation', 'client_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('reservation_client_gropup_id_fkey', 'reservation', type_='foreignkey')
    op.create_foreign_key(None, 'reservation', 'clientgroup', ['client_group_id'], ['id'])
    op.drop_column('reservation', 'client_gropup_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('client_gropup_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reservation', type_='foreignkey')
    op.create_foreign_key('reservation_client_gropup_id_fkey', 'reservation', 'clientgroup', ['client_gropup_id'], ['id'])
    op.alter_column('reservation', 'client_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('reservation', 'client_group_id')
    op.drop_column('client', 'identification')
    # ### end Alembic commands ###
