"""add

Revision ID: acd09a309f4b
Revises: a561558605e7
Create Date: 2025-03-02 23:54:14.169249

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'acd09a309f4b'
down_revision = 'a561558605e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('client_guardian_id_fkey', 'client', type_='foreignkey')
    op.drop_column('client', 'guardian_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('guardian_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('client_guardian_id_fkey', 'client', 'client', ['guardian_id'], ['id'])
    # ### end Alembic commands ###
