"""add

Revision ID: c74a4690ddc4
Revises: ce4f297850c4
Create Date: 2025-02-16 09:09:01.671799

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c74a4690ddc4'
down_revision = 'ce4f297850c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientgroup',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientgroupadminlink',
    sa.Column('client_group_id', sa.Uuid(), nullable=False),
    sa.Column('admin_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['client_group_id'], ['clientgroup.id'], ),
    sa.PrimaryKeyConstraint('client_group_id', 'admin_id')
    )
    op.create_table('qrcode',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.add_column('client', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.add_column('client', sa.Column('group_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'client', 'clientgroup', ['group_id'], ['id'])
    op.create_foreign_key(None, 'client', 'user', ['user_id'], ['id'])
    op.add_column('subscription', sa.Column('client_group_id', sa.Uuid(), nullable=False))
    op.drop_constraint('subscription_client_id_fkey', 'subscription', type_='foreignkey')
    op.create_foreign_key(None, 'subscription', 'clientgroup', ['client_group_id'], ['id'])
    op.drop_column('subscription', 'client_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'subscription', type_='foreignkey')
    op.create_foreign_key('subscription_client_id_fkey', 'subscription', 'client', ['client_id'], ['id'])
    op.drop_column('subscription', 'client_group_id')
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_column('client', 'group_id')
    op.drop_column('client', 'user_id')
    op.drop_table('qrcode')
    op.drop_table('clientgroupadminlink')
    op.drop_table('clientgroup')
    # ### end Alembic commands ###
