"""Add table and model Form

Revision ID: cbdde05d2fa4
Revises: 8f4dc4cfb5ea
Create Date: 2025-03-20 15:24:11.036916

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cbdde05d2fa4'
down_revision = '8f4dc4cfb5ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('form_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('form_data', sa.JSON(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_form_type'), 'form', ['form_type'], unique=False)
    op.create_index(op.f('ix_form_user_id'), 'form', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_user_id'), table_name='form')
    op.drop_index(op.f('ix_form_form_type'), table_name='form')
    op.drop_table('form')
    # ### end Alembic commands ###
