"""aa

Revision ID: ce4f297850c4
Revises: 7f4e197ad981
Create Date: 2025-02-16 06:03:17.653538

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ce4f297850c4'
down_revision = '7f4e197ad981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('remaining_time', sa.Float(), nullable=True))
    op.drop_column('subscription', 'remaining_hours')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('remaining_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('subscription', 'remaining_time')
    # ### end Alembic commands ###
