"""add

Revision ID: d315f479932e
Revises: c74a4690ddc4
Create Date: 2025-02-16 09:18:54.435872

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd315f479932e'
down_revision = 'c74a4690ddc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('qrcode_client_id_key', 'qrcode', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('qrcode_client_id_key', 'qrcode', ['client_id'])
    # ### end Alembic commands ###
